<?php 

use Zend\Session\Container;
$user_session = new Container('user');

if(!isset($user_session->user_id))
{	
	header('Location:/');exit;
}
else if(isset($user_session->user_id)&&($user_session->user_type==0))
{
	header('Location:/profile');exit;
}
else if(isset($user_session->user_id)&&($user_session->user_type==2))
{
	header('Location:/superuser');exit;
}

?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                                                
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                       // ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')                    
                         ->prependStylesheet($this->basePath() . '/css/style.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        //->prependStylesheet($this->basePath() . '/css/jquery.dataTables.css')
                        ->prependStylesheet($this->basePath() . '/css/demo_page.css')
                        ->prependStylesheet($this->basePath() . '/css/demo_table.css')
                        
                  
                       ?>
     
		<script src="../js/jquery.min.js"></script>
		
		<script src="../js/jquery.dataTables.js"></script>
		<script>

		$(document).ready( function () {
		
		    $('#userstab').dataTable();
		    } );
	</script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        	<div class="container">
                    <div class="navbar-header">
                  	<h1 class="navbar-brand">
                 		Assignment
                 	</h1>
                     </div>
                     <div class="nav-collapse collapse">        
			      <ul class="nav pull-right">
			     <?if($this->layout()->actionName!='newuser'){?>
			      	<li><a href="admin/newuser">New User</a></li>
			      	<?}?>			
				<li><a href="/admin/logout">Logout</a></li>
				
			      </ul>
            		</div>
                </div>
           
        </nav>
        <div class="container" style="margin-top: 20px;background:white;width:90%;">
            <?php echo $this->content; ?>
            
            <footer>
               <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation"><br><br><br></div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
