<?php

use Zend\Session\Container;
$user_session = new Container('user');
if(!isset($user_session->user_id))
{	
	header('Location:/');exit;
}
else if(isset($user_session->user_id)&&($user_session->user_type==1))
{
	header('Location:/admin');exit;
}
else if(isset($user_session->user_id)&&($user_session->user_type==2))
{
	header('Location:/superuser');exit;
}

?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
           // ->appendName('viewport', 'width=device-width, initial-scale=1.0')
           //->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                         
                                   
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                          
                         ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                         ->prependStylesheet($this->basePath() . '/css/style.css')             
                        
                       ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/edit-inline/jquery.editinline.js')
           ->prependFile($this->basePath() . '/js/script.js')
           ->prependFile($this->basePath() . '/js/jquery.min.js')
            
          //  ->prependFile($this->basePath() . '/js/script.js')
            //  ->prependFile($this->basePath() . '/js/jquery.validate.js')
              
           
            
              
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        	<div class="container">
                    <div class="navbar-header">
                  	<h1 class="navbar-brand">
                 		Assignment
                 	</h1>
                 	<div class="nav-collapse collapse">        
			      <ul class="nav pull-right">
			      
				<?if($this->layout()->actionName!='edit'){?>
			      	<li><a href="profile/edit">Edit</a></li><?}?>
				<li><a href="/profile/logout">Log out</a></li>				
				<!--<li><a href="#">services</a></li>
				<li><a href="">agents</a></li>-->
			      </ul>
            		</div>
                </div>         
        </nav>
        <div class="container" style="margin-top: 50px;">
            <?php echo $this->content; ?>       
            <footer>
               <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation"><p><br></p></div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
